### ISSUE TITLE
Conflict with Emeralds to Experience mod

### ISSUE THREAD

**Issue by ExcitedName** [duely/unenchanting#1]
Forge: 14.23.5.2768
Unenchanting: 1.0.0
[Emeralds to ExperienceMod](https://minecraft.curseforge.com/projects/emeralds-to-experience-mod?gameCategorySlug=mc-mods&projectID=274283): 1.1 - 1.12
[Crash Report](https://pastebin.com/DdaNHjAS)

The mod adds the renaming of a Grindstone (Unfinished) to Grindstone in an anvil. When I delete (Unfinished) nothing appears in the output slot. As soon as I backspace the e in Grindstone the game crashes.

I really like the simplicity of this mod.

**Comment by noobanidus** [comment]
This is potentially an issue with any renaming. I'll look into it, thanks!

**Comment by noobanidus** [comment]
Upon investigating, I believe this was fixed with 1.0.1. Can you try [the latest version, 1.1.0 from CurseForge](https://minecraft.curseforge.com/projects/unenchanting/files/2706700) and tell me if it still happens for you?

**Comment by ExcitedName** [comment]
I did some testing. I feel a bit silly I hadn't used the Emeralds to Experience mod in a while and was actually going about it incorrectly. My blunder revealed a bug in your mod. I thought I had checked and was using your newest version. That version does indeed resolve the issue. No more crash upon renaming the item. Thanks for your time and help.
